<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BarcodeLib" Version="3.1.*" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.*" />
    <PackageReference Include="CsvHelper" Version="31.0.*" />
    <PackageReference Include="QRCoder" Version="1.4.*" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.ico" />
    <Resource Include="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="wLabelDesigner.Tests\**\*.cs" />
    <EmbeddedResource Remove="wLabelDesigner.Tests\**\*" />
    <None Remove="wLabelDesigner.Tests\**\*" />
  </ItemGroup>

</Project>
